server:
  port: 8082
  ssl:
    enabled: false

cxf:
  jaxrs:
    component-scan: true
    classes-scan-packages: org.apache.cxf.jaxrs.swagger
  path: "/rest"

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health, info, mappings"
  endpoint:
    health:
      enabled: true
    mappings:
      enabled: true
    info:
      enabled: true

logging:
  file:
    name: /data/ncpeh-mock.log
  level:
    de.gematik.ncpeh: INFO
    org.apache.cxf.services: DEBUG

info:
  app:
    name: '@project.name@'
    version: '@project.version@'
    description: '@project.description@'
