resourcePackages:
  - "de.gematik.ncpeh.api"
modelConverterClasses:
  - "de.gematik.ncpeh.build.NcpehApiModelResolver"
openAPI31: false # there seems to be a bug in Swagger or Jackson, preventing the processing of java.util.Map, when using the 3.1 OpenApi spec version.
openAPI:
  info:
    title: "NCPeH Testinterface"
    version: ${project.version}
    description: "Auf der Schnittstelle werden Operationen definiert, \
      \ um die Ausf端hrung von Usecases des NCPeH-Fachdienstes f端r das Anwendungsszenario Patient Summary Land A \
      \ mit den 端bergebenen Daten am Simulator des NCPeH Land B zu triggern. \
      \ Hinweis: Sobald die Unterst端tzung in der Toollandschaft besser ist (siehe https://openapi.tools/), \
      \ wird die API-Beschreibung auf die OpenApi Version 3.1 angehoben."
    contact:
      name: "gematik GmbH"
      email: "software-development@gematik.de"
      url: "https://www.gematik.de"
    license:
      name: "Apache 2.0"
      url: "https://www.apache.org/licenses/LICENSE-2.0"
